library(sf)
library(sp)
library(rgdal)
library(stars)
library(raster)
library(spData)
library(terra)
library(remotes)
library(maptools)
library(spatstat)
library(rpart)
library(foreign)
library(rgeos)
library(geosphere)
a=raster("D:/nou_rprogramming/new/final data/aspect_baglung.tif")
a
b=st_read("D:/nou_rprogramming/new/final data/landslide_point.shp")
plot(b,add=TRUE)
f=extract(a,b)
f
range(f)
g=reclassify(a,matrix(c(-Inf,4.914727,1,4.914727,65.067436,NA,65.067436,Inf,1),ncol=3,byrow = TRUE),right=TRUE)
plot(g)
hi=rasterToPolygons(g)
hi
plot(hi)
h=spsample(hi,n=89,type="random")
k=st_as_sf(h)

st_write(k,"D:/nou_rprogramming/new/final data/non_landslide_point.shp")
